name: NPM Build Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  npm-build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Started NPM Build Job"
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Checking NodeJs & NPM Versions
        run: |
          echo "Node Version check"
          node -v
          echo "NPM Version check"
          npm -v
      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
          npm install -g @angular/cli
      - name: Build for prod
        run: |
          npm run build && cp CNAME dist
      - name: Upload dist folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: ./dist
  deploy-ghpages:
    runs-on: ubuntu-latest
    needs: npm-build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Checkout repository in the deployment job
      - name: Install gh-pages
        run: npm install -g gh-pages
      - name: Download ./dist folder from previous job
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: ./dist
      - name: Set up Git for deployment
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      - name: Deploy to Github Pages
        run: gh-pages --dist dist --repo="https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/vukkumsp/notes-ui-app.git"